# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-11 03:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_auto_20160811_0218'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannerad',
            name='urldst',
            field=models.CharField(default=True, max_length=255),
        ),
    ]
