# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-11 03:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_bannerad_urldst'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='coverimage',
            field=models.FilePathField(default='https://s.gravatar.com/avatar/468722554fb1b547b8e86d1799d45ae4?s=80&r=g', max_length=200),
        ),
    ]
