# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-11 03:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_auto_20160811_0337'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoverImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coverimage', models.FileField(upload_to='cms/media/postcoverimgs/')),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='coverimage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.CoverImage'),
        ),
    ]
