# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-11 07:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_auto_20160811_0341'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaURLS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=True, max_length=35)),
                ('urldst', models.CharField(default=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TalkURLS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=True, max_length=35)),
                ('urldst', models.CharField(default=True, max_length=255)),
            ],
        ),
    ]
