# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-14 21:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0008_post_post_feature'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=35)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='tag',
            name='styleformat',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='cms.Category'),
        ),
    ]
