# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-14 21:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0009_auto_20160814_2107'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='styleformat',
            new_name='category',
        ),
    ]
